
-- iNB Online Banking – H2 In-Memory Schema
-- Generated: 2026-02-19
-- Notes:
--  * JSON columns are stored as CLOB for broad H2 compatibility.
--  * Some identifiers (USER, ROLE, SESSION, TRANSACTION) are quoted due to SQL keywords.
--  * DESC order in indexes is omitted because H2 ignores sort order in CREATE INDEX.

CREATE SCHEMA IF NOT EXISTS INB;
SET SCHEMA INB;

-- Re-runnable safety: drop existing tables (dependencies cascade)
DROP TABLE IF EXISTS CONFIG_APPROVAL CASCADE;
DROP TABLE IF EXISTS CONFIG_ITEM CASCADE;
DROP TABLE IF EXISTS AUDIT_EVENT CASCADE;
DROP TABLE IF EXISTS FRAUD_ALERT CASCADE;
DROP TABLE IF EXISTS NOTIFICATION CASCADE;
DROP TABLE IF EXISTS RECONCILIATION_ITEM CASCADE;
DROP TABLE IF EXISTS RECONCILIATION_RUN CASCADE;
DROP TABLE IF EXISTS STATEMENT_ARTIFACT CASCADE;
DROP TABLE IF EXISTS STATEMENT_REQUEST CASCADE;
DROP TABLE IF EXISTS "TRANSACTION" CASCADE;
DROP TABLE IF EXISTS CHEQUE_STATUS_HISTORY CASCADE;
DROP TABLE IF EXISTS CHEQUE_DEPOSIT CASCADE;
DROP TABLE IF EXISTS BILL_PAYMENT CASCADE;
DROP TABLE IF EXISTS PAYMENT_SCHEDULE CASCADE;
DROP TABLE IF EXISTS BILL_ACCOUNT CASCADE;
DROP TABLE IF EXISTS BILLER CASCADE;
DROP TABLE IF EXISTS TRANSFER_EXECUTION CASCADE;
DROP TABLE IF EXISTS TRANSFER_INSTRUCTION CASCADE;
DROP TABLE IF EXISTS BENEFICIARY CASCADE;
DROP TABLE IF EXISTS IDEMPOTENCY_KEY CASCADE;
DROP TABLE IF EXISTS ACCOUNT_LIMIT CASCADE;
DROP TABLE IF EXISTS ACCOUNT_BALANCE CASCADE;
DROP TABLE IF EXISTS ACCOUNT CASCADE;
DROP TABLE IF EXISTS KYC_DOCUMENT CASCADE;
DROP TABLE IF EXISTS LOGIN_ATTEMPT CASCADE;
DROP TABLE IF EXISTS "SESSION" CASCADE;
DROP TABLE IF EXISTS USER_ROLE CASCADE;
DROP TABLE IF EXISTS "ROLE" CASCADE;
DROP TABLE IF EXISTS "USER" CASCADE;
DROP TABLE IF EXISTS CUSTOMER CASCADE;

-- 1. CUSTOMER
CREATE TABLE CUSTOMER (
    customer_id UUID PRIMARY KEY,
    username VARCHAR(100) NOT NULL,
    default_pwd VARCHAR(255) NOT NULL,
    full_name VARCHAR(200) NOT NULL,
    address_line1 VARCHAR(255),
    address_line2 VARCHAR(255),
    address_line3 VARCHAR(255),
    city VARCHAR(120) NOT NULL,
    state VARCHAR(120) NOT NULL,
    zip INT NOT NULL,
    account_type VARCHAR(50) NOT NULL,
    pan_number VARCHAR(30) NOT NULL,
    addhaar_num INT NOT NULL,
    dob DATE,
    pan_enc VARBINARY,
    aadhaar_hash VARBINARY(64) NOT NULL,
    phone VARCHAR(20) NOT NULL,
    email VARCHAR(254) NOT NULL,
    preferred_language VARCHAR(10) DEFAULT 'en',
    onboarding_status VARCHAR(30) NOT NULL,
    approved_by UUID,
    approved_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT UQ_CUSTOMER_PAN UNIQUE (pan_enc),
    CONSTRAINT UQ_CUSTOMER_AADHAAR UNIQUE (aadhaar_hash)
);

-- 2. USER (quoted)
CREATE TABLE "USER" (
    user_id UUID PRIMARY KEY,
    customer_id UUID,
    idp_subject VARCHAR(200) NOT NULL,
    username VARCHAR(100) NOT NULL,
    pwd VARCHAR(255),
    email VARCHAR(254),
    phone VARCHAR(20),
    user_type VARCHAR(20) NOT NULL,
    status VARCHAR(20) NOT NULL,
    locked_until TIMESTAMP,
    last_login_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT UQ_USER_USERNAME UNIQUE (username),
    CONSTRAINT UQ_USER_IDP_SUBJECT UNIQUE (idp_subject),
    CONSTRAINT FK_USER_CUSTOMER FOREIGN KEY (customer_id) REFERENCES CUSTOMER(customer_id)
);

-- Add FK from CUSTOMER.approved_by to USER.user_id
ALTER TABLE CUSTOMER
    ADD CONSTRAINT FK_CUSTOMER_APPROVED_BY FOREIGN KEY (approved_by) REFERENCES "USER"(user_id);

-- 3. ROLE (quoted)
CREATE TABLE "ROLE" (
    role_id UUID PRIMARY KEY,
    role_name VARCHAR(50) NOT NULL,
    description VARCHAR(250),
    CONSTRAINT UQ_ROLE_NAME UNIQUE (role_name)
);

-- 4. USER_ROLE (composite PK)
CREATE TABLE USER_ROLE (
    user_id UUID NOT NULL,
    role_id UUID NOT NULL,
    assigned_at TIMESTAMP NOT NULL,
    assigned_by UUID,
    PRIMARY KEY (user_id, role_id),
    CONSTRAINT FK_USER_ROLE_USER FOREIGN KEY (user_id) REFERENCES "USER"(user_id),
    CONSTRAINT FK_USER_ROLE_ROLE FOREIGN KEY (role_id) REFERENCES "ROLE"(role_id),
    CONSTRAINT FK_USER_ROLE_ASSIGNED_BY FOREIGN KEY (assigned_by) REFERENCES "USER"(user_id)
);

-- 5. SESSION (quoted)
CREATE TABLE "SESSION" (
    session_id UUID PRIMARY KEY,
    user_id UUID NOT NULL,
    created_at TIMESTAMP NOT NULL,
    expires_at TIMESTAMP NOT NULL,
    last_seen_at TIMESTAMP NOT NULL,
    ip_address VARCHAR(45) NOT NULL,
    device_fingerprint VARCHAR(200),
    status VARCHAR(20) NOT NULL,
    revoked_reason VARCHAR(120),
    correlation_id VARCHAR(64),
    CONSTRAINT FK_SESSION_USER FOREIGN KEY (user_id) REFERENCES "USER"(user_id)
);

-- 6. LOGIN_ATTEMPT
CREATE TABLE LOGIN_ATTEMPT (
    attempt_id UUID PRIMARY KEY,
    user_id UUID,
    username VARCHAR(100),
    attempt_at TIMESTAMP NOT NULL,
    ip_address VARCHAR(45) NOT NULL,
    device_fingerprint VARCHAR(200),
    outcome VARCHAR(20) NOT NULL,
    failure_reason VARCHAR(50),
    correlation_id VARCHAR(64),
    CONSTRAINT FK_LOGIN_USER FOREIGN KEY (user_id) REFERENCES "USER"(user_id)
);

-- 7. KYC_DOCUMENT
CREATE TABLE KYC_DOCUMENT (
    kyc_doc_id UUID PRIMARY KEY,
    customer_id UUID NOT NULL,
    doc_type VARCHAR(30) NOT NULL,
    object_uri VARCHAR(500) NOT NULL,
    content_hash VARBINARY(32) NOT NULL,
    mime_type VARCHAR(80) NOT NULL,
    uploaded_at TIMESTAMP NOT NULL,
    uploaded_by UUID,
    status VARCHAR(20) NOT NULL,
    verified_by UUID,
    verified_at TIMESTAMP,
    CONSTRAINT FK_KYC_CUSTOMER FOREIGN KEY (customer_id) REFERENCES CUSTOMER(customer_id),
    CONSTRAINT FK_KYC_UPLOADED_BY FOREIGN KEY (uploaded_by) REFERENCES "USER"(user_id),
    CONSTRAINT FK_KYC_VERIFIED_BY FOREIGN KEY (verified_by) REFERENCES "USER"(user_id)
);

-- 8. ACCOUNT
CREATE TABLE ACCOUNT (
    account_id UUID PRIMARY KEY,
    customer_id UUID NOT NULL,
    account_number VARCHAR(30) NOT NULL,
    account_type VARCHAR(20) NOT NULL,
    branch_code VARCHAR(20) NOT NULL,
    currency CHAR(3) NOT NULL,
    status VARCHAR(20) NOT NULL,
    opened_at DATE NOT NULL,
    closed_at DATE,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT UQ_ACCOUNT_NUMBER UNIQUE (account_number),
    CONSTRAINT FK_ACCOUNT_CUSTOMER FOREIGN KEY (customer_id) REFERENCES CUSTOMER(customer_id)
);

-- 9. ACCOUNT_BALANCE
CREATE TABLE ACCOUNT_BALANCE (
    account_id UUID PRIMARY KEY,
    available_balance DECIMAL(18,2) NOT NULL,
    ledger_balance DECIMAL(18,2) NOT NULL,
    as_of TIMESTAMP NOT NULL,
    overdraft_used DECIMAL(18,2) DEFAULT 0 NOT NULL,
    CONSTRAINT FK_BALANCE_ACCOUNT FOREIGN KEY (account_id) REFERENCES ACCOUNT(account_id)
);

-- 10. ACCOUNT_LIMIT
CREATE TABLE ACCOUNT_LIMIT (
    limit_id UUID PRIMARY KEY,
    account_id UUID NOT NULL,
    limit_type VARCHAR(40) NOT NULL,
    limit_value DECIMAL(18,2) NOT NULL,
    currency CHAR(3) NOT NULL,
    effective_from TIMESTAMP NOT NULL,
    effective_to TIMESTAMP,
    configured_by UUID NOT NULL,
    configured_at TIMESTAMP NOT NULL,
    CONSTRAINT FK_LIMIT_ACCOUNT FOREIGN KEY (account_id) REFERENCES ACCOUNT(account_id),
    CONSTRAINT FK_LIMIT_CONFIGURED_BY FOREIGN KEY (configured_by) REFERENCES "USER"(user_id)
);

-- 11. IDEMPOTENCY_KEY
CREATE TABLE IDEMPOTENCY_KEY (
    key_id UUID PRIMARY KEY,
    owner_user_id UUID NOT NULL,
    key_hash VARBINARY(32) NOT NULL,
    scope VARCHAR(30) NOT NULL,
    request_fingerprint VARBINARY(32) NOT NULL,
    status VARCHAR(20) NOT NULL,
    response_ref VARCHAR(200),
    created_at TIMESTAMP NOT NULL,
    expires_at TIMESTAMP NOT NULL,
    CONSTRAINT UQ_IDEMPOTENCY_HASH UNIQUE (key_hash),
    CONSTRAINT FK_IDEMPOTENCY_OWNER FOREIGN KEY (owner_user_id) REFERENCES "USER"(user_id)
);

-- 12. BENEFICIARY
CREATE TABLE BENEFICIARY (
    beneficiary_id UUID PRIMARY KEY,
    customer_id UUID NOT NULL,
    name VARCHAR(200) NOT NULL,
    bank_name VARCHAR(200),
    ifsc VARCHAR(16),
    account_number VARCHAR(30) NOT NULL,
    beneficiary_type VARCHAR(20) NOT NULL,
    status VARCHAR(20) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT FK_BENEFICIARY_CUSTOMER FOREIGN KEY (customer_id) REFERENCES CUSTOMER(customer_id)
);

-- 13. TRANSFER_INSTRUCTION
CREATE TABLE TRANSFER_INSTRUCTION (
    transfer_id UUID PRIMARY KEY,
    customer_id UUID NOT NULL,
    source_account_id UUID NOT NULL,
    beneficiary_id UUID NOT NULL,
    amount DECIMAL(18,2) NOT NULL,
    currency CHAR(3) NOT NULL,
    mode VARCHAR(20) NOT NULL,
    status VARCHAR(20) NOT NULL,
    idempotency_key_id UUID NOT NULL,
    risk_score DECIMAL(5,2),
    created_at TIMESTAMP NOT NULL,
    completed_at TIMESTAMP,
    reference VARCHAR(64),
    correlation_id VARCHAR(64),
    CONSTRAINT UQ_TRF_REFERENCE UNIQUE (reference),
    CONSTRAINT FK_TRF_CUSTOMER FOREIGN KEY (customer_id) REFERENCES CUSTOMER(customer_id),
    CONSTRAINT FK_TRF_SOURCE_ACCOUNT FOREIGN KEY (source_account_id) REFERENCES ACCOUNT(account_id),
    CONSTRAINT FK_TRF_BENEFICIARY FOREIGN KEY (beneficiary_id) REFERENCES BENEFICIARY(beneficiary_id),
    CONSTRAINT FK_TRF_IDEMPOTENCY FOREIGN KEY (idempotency_key_id) REFERENCES IDEMPOTENCY_KEY(key_id)
);

-- 14. TRANSFER_EXECUTION
CREATE TABLE TRANSFER_EXECUTION (
    execution_id UUID PRIMARY KEY,
    transfer_id UUID NOT NULL,
    attempt_no INT NOT NULL,
    network VARCHAR(20) NOT NULL,
    external_reference VARCHAR(120),
    status VARCHAR(20) NOT NULL,
    sent_at TIMESTAMP,
    updated_at TIMESTAMP NOT NULL,
    failure_code VARCHAR(40),
    CONSTRAINT FK_TRF_EXEC_TRANSFER FOREIGN KEY (transfer_id) REFERENCES TRANSFER_INSTRUCTION(transfer_id)
);

-- 15. BILLER
CREATE TABLE BILLER (
    biller_id UUID PRIMARY KEY,
    name VARCHAR(200) NOT NULL,
    category VARCHAR(50),
    api_reference VARCHAR(100) NOT NULL,
    active BOOLEAN NOT NULL,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT UQ_BILLER_APIREF UNIQUE (api_reference)
);

-- 16. BILL_ACCOUNT
CREATE TABLE BILL_ACCOUNT (
    bill_account_id UUID PRIMARY KEY,
    customer_id UUID NOT NULL,
    biller_id UUID NOT NULL,
    consumer_number VARCHAR(60) NOT NULL,
    nickname VARCHAR(80),
    status VARCHAR(20) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT UQ_BILLACC UNIQUE (biller_id, consumer_number, customer_id),
    CONSTRAINT FK_BILLACC_CUSTOMER FOREIGN KEY (customer_id) REFERENCES CUSTOMER(customer_id),
    CONSTRAINT FK_BILLACC_BILLER FOREIGN KEY (biller_id) REFERENCES BILLER(biller_id)
);

-- 17. PAYMENT_SCHEDULE
CREATE TABLE PAYMENT_SCHEDULE (
    schedule_id UUID PRIMARY KEY,
    bill_account_id UUID NOT NULL,
    frequency VARCHAR(20) NOT NULL,
    day_of_month INT NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE,
    max_amount DECIMAL(18,2),
    status VARCHAR(20) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT FK_SCHED_BILLACC FOREIGN KEY (bill_account_id) REFERENCES BILL_ACCOUNT(bill_account_id)
);

-- 18. BILL_PAYMENT
CREATE TABLE BILL_PAYMENT (
    bill_payment_id UUID PRIMARY KEY,
    customer_id UUID NOT NULL,
    source_account_id UUID NOT NULL,
    bill_account_id UUID NOT NULL,
    amount DECIMAL(18,2) NOT NULL,
    currency CHAR(3) NOT NULL,
    is_recurring BOOLEAN NOT NULL,
    schedule_id UUID,
    gateway VARCHAR(30) NOT NULL,
    gateway_reference VARCHAR(100),
    status VARCHAR(20) NOT NULL,
    idempotency_key_id UUID NOT NULL,
    created_at TIMESTAMP NOT NULL,
    completed_at TIMESTAMP,
    reference VARCHAR(64),
    CONSTRAINT UQ_BP_REF UNIQUE (reference),
    CONSTRAINT FK_BP_CUSTOMER FOREIGN KEY (customer_id) REFERENCES CUSTOMER(customer_id),
    CONSTRAINT FK_BP_SRC_ACCOUNT FOREIGN KEY (source_account_id) REFERENCES ACCOUNT(account_id),
    CONSTRAINT FK_BP_BILL_ACCOUNT FOREIGN KEY (bill_account_id) REFERENCES BILL_ACCOUNT(bill_account_id),
    CONSTRAINT FK_BP_SCHEDULE FOREIGN KEY (schedule_id) REFERENCES PAYMENT_SCHEDULE(schedule_id),
    CONSTRAINT FK_BP_IDEMPOTENCY FOREIGN KEY (idempotency_key_id) REFERENCES IDEMPOTENCY_KEY(key_id)
);

-- 19. CHEQUE_DEPOSIT
CREATE TABLE CHEQUE_DEPOSIT (
    cheque_deposit_id UUID PRIMARY KEY,
    customer_id UUID NOT NULL,
    account_id UUID NOT NULL,
    depositor_name VARCHAR(150),
    cheque_number VARCHAR(30) NOT NULL,
    cheque_date DATE,
    drawer_bank VARCHAR(200),
    branch_name VARCHAR(200),
    amount DECIMAL(18,2) NOT NULL,
    currency CHAR(3) NOT NULL,
    submitted_at TIMESTAMP NOT NULL,
    current_status VARCHAR(30) NOT NULL,
    clearance_sla_days INT NOT NULL,
    bounce_penalty_amount DECIMAL(18,2),
    remarks VARCHAR(250),
    attachment_name VARCHAR(255),
    attmt_doc BLOB,
    attachment_blob_url VARCHAR(1024),
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT FK_CHQ_CUSTOMER FOREIGN KEY (customer_id) REFERENCES CUSTOMER(customer_id),
    CONSTRAINT FK_CHQ_ACCOUNT FOREIGN KEY (account_id) REFERENCES ACCOUNT(account_id)
);

-- 20. CHEQUE_STATUS_HISTORY
CREATE TABLE CHEQUE_STATUS_HISTORY (
    history_id UUID PRIMARY KEY,
    cheque_deposit_id UUID NOT NULL,
    old_status VARCHAR(30) NOT NULL,
    new_status VARCHAR(30) NOT NULL,
    changed_by UUID NOT NULL,
    changed_at TIMESTAMP NOT NULL,
    remarks VARCHAR(250),
    CONSTRAINT FK_CHQ_HIST_DEPOSIT FOREIGN KEY (cheque_deposit_id) REFERENCES CHEQUE_DEPOSIT(cheque_deposit_id),
    CONSTRAINT FK_CHQ_HIST_CHANGED_BY FOREIGN KEY (changed_by) REFERENCES "USER"(user_id)
);

-- 21. TRANSACTION (quoted)
CREATE TABLE "TRANSACTION" (
    txn_id UUID PRIMARY KEY,
    account_id UUID NOT NULL,
    txn_type VARCHAR(30) NOT NULL,
    direction CHAR(1) NOT NULL,
    amount DECIMAL(18,2) NOT NULL,
    currency CHAR(3) NOT NULL,
    posted_at TIMESTAMP NOT NULL,
    value_date DATE NOT NULL,
    status VARCHAR(20) NOT NULL,
    reference VARCHAR(64),
    related_entity_type VARCHAR(40),
    related_entity_id UUID,
    narration VARCHAR(250),
    correlation_id VARCHAR(64),
    CONSTRAINT UQ_TXN_REFERENCE UNIQUE (reference),
    CONSTRAINT FK_TXN_ACCOUNT FOREIGN KEY (account_id) REFERENCES ACCOUNT(account_id)
);

-- 22. STATEMENT_REQUEST
CREATE TABLE STATEMENT_REQUEST (
    statement_req_id UUID PRIMARY KEY,
    account_id UUID NOT NULL,
    request_type VARCHAR(20) NOT NULL,
    from_date DATE,
    to_date DATE,
    format VARCHAR(10) NOT NULL,
    status VARCHAR(20) NOT NULL,
    created_by UUID NOT NULL,
    created_at TIMESTAMP NOT NULL,
    completed_at TIMESTAMP,
    correlation_id VARCHAR(64),
    CONSTRAINT FK_STMT_ACCOUNT FOREIGN KEY (account_id) REFERENCES ACCOUNT(account_id),
    CONSTRAINT FK_STMT_CREATED_BY FOREIGN KEY (created_by) REFERENCES "USER"(user_id)
);

-- 23. STATEMENT_ARTIFACT
CREATE TABLE STATEMENT_ARTIFACT (
    artifact_id UUID PRIMARY KEY,
    statement_req_id UUID NOT NULL,
    object_uri VARCHAR(500) NOT NULL,
    content_hash VARBINARY(32) NOT NULL,
    size_bytes BIGINT NOT NULL,
    generated_at TIMESTAMP NOT NULL,
    expires_at TIMESTAMP,
    mime_type VARCHAR(80) NOT NULL,
    CONSTRAINT FK_STMT_ART_REQ FOREIGN KEY (statement_req_id) REFERENCES STATEMENT_REQUEST(statement_req_id)
);

-- 24. RECONCILIATION_RUN
CREATE TABLE RECONCILIATION_RUN (
    recon_run_id UUID PRIMARY KEY,
    run_type VARCHAR(20) NOT NULL,
    business_date DATE NOT NULL,
    status VARCHAR(20) NOT NULL,
    started_at TIMESTAMP NOT NULL,
    completed_at TIMESTAMP,
    generated_by UUID NOT NULL,
    report_object_uri VARCHAR(500),
    correlation_id VARCHAR(64),
    CONSTRAINT FK_RECON_RUN_GEN_BY FOREIGN KEY (generated_by) REFERENCES "USER"(user_id)
);

-- 25. RECONCILIATION_ITEM
CREATE TABLE RECONCILIATION_ITEM (
    recon_item_id UUID PRIMARY KEY,
    recon_run_id UUID NOT NULL,
    txn_id UUID NOT NULL,
    match_status VARCHAR(20) NOT NULL,
    notes VARCHAR(250),
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT FK_RECON_ITEM_RUN FOREIGN KEY (recon_run_id) REFERENCES RECONCILIATION_RUN(recon_run_id),
    CONSTRAINT FK_RECON_ITEM_TXN FOREIGN KEY (txn_id) REFERENCES "TRANSACTION"(txn_id)
);

-- 26. NOTIFICATION
CREATE TABLE NOTIFICATION (
    notification_id UUID PRIMARY KEY,
    recipient_user_id UUID,
    channel VARCHAR(10) NOT NULL,
    template_code VARCHAR(50) NOT NULL,
    destination VARCHAR(254) NOT NULL,
    payload_ref VARCHAR(200),
    status VARCHAR(20) NOT NULL,
    provider_message_id VARCHAR(120),
    related_entity_type VARCHAR(40),
    related_entity_id UUID,
    created_at TIMESTAMP NOT NULL,
    sent_at TIMESTAMP,
    delivered_at TIMESTAMP,
    CONSTRAINT FK_NOTIFICATION_RECIP FOREIGN KEY (recipient_user_id) REFERENCES "USER"(user_id)
);

-- 27. FRAUD_ALERT
CREATE TABLE FRAUD_ALERT (
    fraud_alert_id UUID PRIMARY KEY,
    entity_type VARCHAR(40) NOT NULL,
    entity_id UUID NOT NULL,
    risk_score DECIMAL(5,2) NOT NULL,
    rule_code VARCHAR(50) NOT NULL,
    status VARCHAR(20) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    reviewed_by UUID,
    reviewed_at TIMESTAMP,
    outcome VARCHAR(30),
    notes VARCHAR(500),
    CONSTRAINT FK_FRAUD_REVIEWED_BY FOREIGN KEY (reviewed_by) REFERENCES "USER"(user_id)
);

-- 28. AUDIT_EVENT
CREATE TABLE AUDIT_EVENT (
    audit_id UUID PRIMARY KEY,
    actor_user_id UUID NOT NULL,
    actor_role VARCHAR(50) NOT NULL,
    action VARCHAR(80) NOT NULL,
    entity_type VARCHAR(60) NOT NULL,
    entity_id UUID NOT NULL,
    outcome VARCHAR(20) NOT NULL,
    timestamp TIMESTAMP NOT NULL,
    ip_address VARCHAR(45) NOT NULL,
    device_metadata VARCHAR(400),
    correlation_id VARCHAR(64),
    details_json CLOB,
    CONSTRAINT FK_AUDIT_USER FOREIGN KEY (actor_user_id) REFERENCES "USER"(user_id)
);

-- 29. CONFIG_ITEM
CREATE TABLE CONFIG_ITEM (
    config_id UUID PRIMARY KEY,
    config_key VARCHAR(100) NOT NULL,
    scope_type VARCHAR(20) NOT NULL,
    scope_id VARCHAR(60),
    value_json CLOB NOT NULL,
    version INT NOT NULL,
    status VARCHAR(20) NOT NULL,
    effective_from TIMESTAMP NOT NULL,
    effective_to TIMESTAMP,
    created_by UUID NOT NULL,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT FK_CONFIG_CREATED_BY FOREIGN KEY (created_by) REFERENCES "USER"(user_id)
);

-- 30. CONFIG_APPROVAL
CREATE TABLE CONFIG_APPROVAL (
    approval_id UUID PRIMARY KEY,
    config_id UUID NOT NULL,
    requested_by UUID NOT NULL,
    requested_at TIMESTAMP NOT NULL,
    approved_by UUID,
    approved_at TIMESTAMP,
    status VARCHAR(20) NOT NULL,
    comment VARCHAR(250),
    CONSTRAINT FK_CFG_APPR_CONFIG FOREIGN KEY (config_id) REFERENCES CONFIG_ITEM(config_id),
    CONSTRAINT FK_CFG_APPR_REQ_BY FOREIGN KEY (requested_by) REFERENCES "USER"(user_id),
    CONSTRAINT FK_CFG_APPR_APPR_BY FOREIGN KEY (approved_by) REFERENCES "USER"(user_id)
);

-- =====================
-- Indexes
-- =====================

-- CUSTOMER indexes
CREATE INDEX IF NOT EXISTS IX_CUSTOMER_STATUS ON CUSTOMER(onboarding_status, created_at);
CREATE INDEX IF NOT EXISTS IX_CUSTOMER_PHONE ON CUSTOMER(phone);

-- USER indexes
CREATE INDEX IF NOT EXISTS IX_USER_TYPE_STATUS ON "USER"(user_type, status);
CREATE INDEX IF NOT EXISTS IX_USER_CUSTOMER ON "USER"(customer_id);

-- USER_ROLE indexes
CREATE INDEX IF NOT EXISTS IX_USER_ROLE_ROLE ON USER_ROLE(role_id);

-- SESSION indexes
CREATE INDEX IF NOT EXISTS IX_SESSION_USER_STATUS ON "SESSION"(user_id, status, expires_at);
CREATE INDEX IF NOT EXISTS IX_SESSION_EXPIRES ON "SESSION"(expires_at);
CREATE INDEX IF NOT EXISTS IX_SESSION_CORR ON "SESSION"(correlation_id);

-- LOGIN_ATTEMPT indexes
CREATE INDEX IF NOT EXISTS IX_LOGIN_USER_TIME ON LOGIN_ATTEMPT(user_id, attempt_at);
CREATE INDEX IF NOT EXISTS IX_LOGIN_IP_TIME ON LOGIN_ATTEMPT(ip_address, attempt_at);
CREATE INDEX IF NOT EXISTS IX_LOGIN_USERNAME_TIME ON LOGIN_ATTEMPT(username, attempt_at);
CREATE INDEX IF NOT EXISTS IX_LOGIN_OUTCOME_TIME ON LOGIN_ATTEMPT(outcome, attempt_at);

-- KYC_DOCUMENT indexes
CREATE INDEX IF NOT EXISTS IX_KYC_CUSTOMER_TYPE ON KYC_DOCUMENT(customer_id, doc_type);
CREATE INDEX IF NOT EXISTS IX_KYC_STATUS ON KYC_DOCUMENT(status, uploaded_at);

-- ACCOUNT indexes
CREATE INDEX IF NOT EXISTS IX_ACCOUNT_CUSTOMER ON ACCOUNT(customer_id);
CREATE INDEX IF NOT EXISTS IX_ACCOUNT_BRANCH ON ACCOUNT(branch_code);
CREATE INDEX IF NOT EXISTS IX_ACCOUNT_STATUS ON ACCOUNT(status);

-- ACCOUNT_BALANCE indexes
CREATE INDEX IF NOT EXISTS IX_BALANCE_ASOF ON ACCOUNT_BALANCE(as_of);

-- ACCOUNT_LIMIT indexes
CREATE INDEX IF NOT EXISTS IX_LIMIT_ACCOUNT_TYPE ON ACCOUNT_LIMIT(account_id, limit_type, effective_from);

-- IDEMPOTENCY_KEY indexes
CREATE INDEX IF NOT EXISTS IX_IDEMPOTENCY_OWNER ON IDEMPOTENCY_KEY(owner_user_id, created_at);
CREATE INDEX IF NOT EXISTS IX_IDEMPOTENCY_EXPIRES ON IDEMPOTENCY_KEY(expires_at);

-- TRANSACTION indexes
CREATE INDEX IF NOT EXISTS IX_TXN_ACCOUNT_POSTED ON "TRANSACTION"(account_id, posted_at);
CREATE INDEX IF NOT EXISTS IX_TXN_ACCOUNT_VALUE ON "TRANSACTION"(account_id, value_date);
CREATE INDEX IF NOT EXISTS IX_TXN_TYPE_TIME ON "TRANSACTION"(txn_type, posted_at);
CREATE INDEX IF NOT EXISTS IX_TXN_RELATED ON "TRANSACTION"(related_entity_type, related_entity_id);
CREATE INDEX IF NOT EXISTS IX_TXN_CORR ON "TRANSACTION"(correlation_id);

-- BENEFICIARY indexes
CREATE INDEX IF NOT EXISTS IX_BENE_CUSTOMER ON BENEFICIARY(customer_id, status);
CREATE INDEX IF NOT EXISTS IX_BENE_ACCT ON BENEFICIARY(account_number);

-- TRANSFER_INSTRUCTION indexes
CREATE INDEX IF NOT EXISTS IX_TRF_SRC_TIME ON TRANSFER_INSTRUCTION(source_account_id, created_at);
CREATE INDEX IF NOT EXISTS IX_TRF_CUST_TIME ON TRANSFER_INSTRUCTION(customer_id, created_at);
CREATE INDEX IF NOT EXISTS IX_TRF_STATUS_TIME ON TRANSFER_INSTRUCTION(status, created_at);

-- TRANSFER_EXECUTION indexes
CREATE INDEX IF NOT EXISTS IX_TRF_EXEC_TRF ON TRANSFER_EXECUTION(transfer_id, attempt_no);
CREATE INDEX IF NOT EXISTS IX_TRF_EXEC_STATUS ON TRANSFER_EXECUTION(status, updated_at);

-- BILLER indexes
CREATE INDEX IF NOT EXISTS IX_BILLER_ACTIVE ON BILLER(active, name);

-- BILL_ACCOUNT indexes
CREATE INDEX IF NOT EXISTS IX_BILLACC_CUST ON BILL_ACCOUNT(customer_id, status);
CREATE INDEX IF NOT EXISTS IX_BILLACC_BILLER ON BILL_ACCOUNT(biller_id);

-- PAYMENT_SCHEDULE indexes
CREATE INDEX IF NOT EXISTS IX_SCHED_BILLACC ON PAYMENT_SCHEDULE(bill_account_id, status);
CREATE INDEX IF NOT EXISTS IX_SCHED_RUN ON PAYMENT_SCHEDULE(status, day_of_month);

-- BILL_PAYMENT indexes
CREATE INDEX IF NOT EXISTS IX_BP_SRC_TIME ON BILL_PAYMENT(source_account_id, created_at);
CREATE INDEX IF NOT EXISTS IX_BP_STATUS_TIME ON BILL_PAYMENT(status, created_at);

-- CHEQUE_DEPOSIT indexes
CREATE INDEX IF NOT EXISTS IX_CHQ_ACC_TIME ON CHEQUE_DEPOSIT(account_id, submitted_at);
CREATE INDEX IF NOT EXISTS IX_CHQ_STATUS_TIME ON CHEQUE_DEPOSIT(current_status, submitted_at);

-- CHEQUE_STATUS_HISTORY indexes
CREATE INDEX IF NOT EXISTS IX_CHQ_HIST_DEP_TIME ON CHEQUE_STATUS_HISTORY(cheque_deposit_id, changed_at);

-- STATEMENT_REQUEST indexes
CREATE INDEX IF NOT EXISTS IX_STMT_ACC_TIME ON STATEMENT_REQUEST(account_id, created_at);
CREATE INDEX IF NOT EXISTS IX_STMT_STATUS_TIME ON STATEMENT_REQUEST(status, created_at);

-- STATEMENT_ARTIFACT indexes
CREATE INDEX IF NOT EXISTS IX_STMT_ART_REQ ON STATEMENT_ARTIFACT(statement_req_id);
CREATE INDEX IF NOT EXISTS IX_STMT_ART_GEN ON STATEMENT_ARTIFACT(generated_at);

-- RECONCILIATION_RUN indexes
CREATE INDEX IF NOT EXISTS IX_RECON_DATE ON RECONCILIATION_RUN(business_date, run_type);
CREATE INDEX IF NOT EXISTS IX_RECON_STATUS ON RECONCILIATION_RUN(status, started_at);

-- RECONCILIATION_ITEM indexes
CREATE INDEX IF NOT EXISTS IX_RECON_ITEM_RUN ON RECONCILIATION_ITEM(recon_run_id, match_status);
CREATE INDEX IF NOT EXISTS IX_RECON_ITEM_TXN ON RECONCILIATION_ITEM(txn_id);

-- NOTIFICATION indexes
CREATE INDEX IF NOT EXISTS IX_NOTIF_RECIP_TIME ON NOTIFICATION(recipient_user_id, created_at);
CREATE INDEX IF NOT EXISTS IX_NOTIF_STATUS_TIME ON NOTIFICATION(status, created_at);
CREATE INDEX IF NOT EXISTS IX_NOTIF_RELATED ON NOTIFICATION(related_entity_type, related_entity_id);

-- FRAUD_ALERT indexes
CREATE INDEX IF NOT EXISTS IX_FRAUD_ENTITY ON FRAUD_ALERT(entity_type, entity_id);
CREATE INDEX IF NOT EXISTS IX_FRAUD_STATUS_TIME ON FRAUD_ALERT(status, created_at);
CREATE INDEX IF NOT EXISTS IX_FRAUD_SCORE ON FRAUD_ALERT(risk_score);

-- AUDIT_EVENT indexes
CREATE INDEX IF NOT EXISTS IX_AUDIT_TIME ON AUDIT_EVENT(timestamp);
CREATE INDEX IF NOT EXISTS IX_AUDIT_ACTOR_TIME ON AUDIT_EVENT(actor_user_id, timestamp);
CREATE INDEX IF NOT EXISTS IX_AUDIT_ENTITY ON AUDIT_EVENT(entity_type, entity_id, timestamp);
CREATE INDEX IF NOT EXISTS IX_AUDIT_ACTION_TIME ON AUDIT_EVENT(action, timestamp);
CREATE INDEX IF NOT EXISTS IX_AUDIT_OUTCOME_TIME ON AUDIT_EVENT(outcome, timestamp);
CREATE INDEX IF NOT EXISTS IX_AUDIT_CORR ON AUDIT_EVENT(correlation_id);

-- CONFIG_ITEM indexes
CREATE INDEX IF NOT EXISTS IX_CONFIG_KEY_SCOPE ON CONFIG_ITEM(config_key, scope_type, scope_id, status);
CREATE INDEX IF NOT EXISTS IX_CONFIG_EFFECTIVE ON CONFIG_ITEM(effective_from);

-- CONFIG_APPROVAL indexes
CREATE INDEX IF NOT EXISTS IX_CFG_APPR_STATUS ON CONFIG_APPROVAL(status, requested_at);
CREATE INDEX IF NOT EXISTS IX_CFG_APPR_CONFIG ON CONFIG_APPROVAL(config_id);

